services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    ports:
        - "5432:5432"
  web:
    build: .
    restart: always
    env_file:
      - .env
    environment:
        - DB_HOST=${DB_HOST_CONTAINER}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
    depends_on:
      - db
    ports:
      - "8080:8080"
