spring:
  output:
    ansi:
      enabled: always
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      add-mappings: true
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"
server:
  error:
    include-stacktrace: never
    include-message: always
upload-dir: ${user.home}/uploads
